#!/usr/bin/env python3
"""
Simplified deployment script with better error handling
"""

import os
import sys
import traceback
from flask import Flask, render_template, request, jsonify
from flask_cors import CORS

# Try to import required modules
try:
    import pandas as pd
    import numpy as np
    print("✅ pandas and numpy imported successfully")
except ImportError as e:
    print(f"❌ Error importing pandas/numpy: {e}")
    sys.exit(1)

try:
    from pyngrok import ngrok
    NGROK_AVAILABLE = True
    print("✅ pyngrok imported successfully")
except ImportError:
    NGROK_AVAILABLE = False
    print("⚠️ pyngrok not available, will run local only")

# Try to import our modules
try:
    from main_app import GeneticModelTrainer
    print("✅ GeneticModelTrainer imported successfully")
except ImportError as e:
    print(f"❌ Error importing GeneticModelTrainer: {e}")
    print("🔄 Will create mock model for testing")
    GeneticModelTrainer = None

app = Flask(__name__, static_folder='assets', static_url_path='/assets')
CORS(app)

# Global model variable
model = None

def load_model():
    """Load the genetic model with error handling"""
    global model
    if GeneticModelTrainer is None:
        print("⚠️ Using mock model for testing")
        return True
    
    try:
        model = GeneticModelTrainer.load_saved_model(
            'models/genetic_model.h5',
            'models/preprocessors.pkl'
        )
        print("✅ Model loaded successfully")
        return True
    except Exception as e:
        print(f"❌ Failed to load model: {str(e)}")
        print("🔄 Will use mock predictions")
        return True  # Continue anyway for testing

@app.route('/')
def index():
    """Serve the main genetic analysis page"""
    try:
        return render_template('genetic_website.html')
    except Exception as e:
        return f"Error loading template: {str(e)}"

@app.route('/api/health')
def health_check():
    """Health check endpoint"""
    return jsonify({
        'status': 'healthy',
        'model_loaded': model is not None,
        'service': 'GrenckDevs Genetic Analysis Platform',
        'version': 'simplified'
    })

@app.route('/api/analyze', methods=['POST'])
def analyze_genetics():
    """Simplified analysis endpoint"""
    try:
        data = request.get_json()
        
        # Basic validation
        required_fields = ['disorder', 'parent1_sex', 'parent2_sex', 
                          'parent1_genotype', 'parent2_genotype', 'generations']
        
        for field in required_fields:
            if field not in data or not data[field]:
                return jsonify({
                    'success': False, 
                    'errors': [f'Missing required field: {field}']
                }), 400
        
        # Mock analysis for testing
        import random
        probability = random.uniform(10, 90)  # Random probability for testing
        
        # Create a simple base64 placeholder image
        placeholder_image = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjBmMGYwIi8+CiAgPHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZmlsbD0iIzMzMyIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkdlbmV0aWMgQW5hbHlzaXMgUGxhY2Vob2xkZXI8L3RleHQ+Cjwvc3ZnPg=="
        
        return jsonify({
            'success': True,
            'results': {
                'disorder': data['disorder'],
                'probability': probability,
                'punnett_image': placeholder_image,
                'input_data': data,
                'note': 'This is a test version with mock data'
            }
        })
        
    except Exception as e:
        print(f"Analysis error: {str(e)}")
        traceback.print_exc()
        return jsonify({
            'success': False, 
            'error': f'Analysis failed: {str(e)}'
        }), 500

@app.route('/api/export-report', methods=['POST'])
def export_report():
    """Simplified export endpoint"""
    try:
        data = request.get_json()
        
        # Create a simple text report
        report_content = f"""
GrenckDevs Genetic Analysis Report (Test Version)
================================================

Disorder: {data.get('disorder', 'Unknown')}
Probability: {data.get('probability', 0):.2f}%

This is a test report. The full version would include:
- Detailed genetic analysis
- Punnett square visualization
- Professional formatting
- Medical recommendations

Generated by GrenckDevs Genetic Analysis Platform
        """
        
        from io import BytesIO
        from flask import send_file
        
        # Create a simple text file
        buffer = BytesIO()
        buffer.write(report_content.encode('utf-8'))
        buffer.seek(0)
        
        return send_file(
            buffer,
            as_attachment=True,
            download_name='GrenckDevs_Test_Report.txt',
            mimetype='text/plain'
        )
        
    except Exception as e:
        print(f"Export error: {str(e)}")
        return jsonify({
            'success': False, 
            'error': f'Export failed: {str(e)}'
        }), 500

def start_ngrok_tunnel(port=5000):
    """Start ngrok tunnel"""
    if not NGROK_AVAILABLE:
        return None
    
    try:
        ngrok.kill()
        tunnel = ngrok.connect(port)
        return tunnel.public_url
    except Exception as e:
        print(f"❌ ngrok failed: {str(e)}")
        return None

def main():
    """Main function with comprehensive error handling"""
    print("🧬 GrenckDevs Genetic Analysis Platform - Simplified Deployment")
    print("="*70)
    
    # Load model
    print("📊 Loading genetic analysis model...")
    load_model()
    
    # Start ngrok if available
    port = 5000
    public_url = None
    
    if NGROK_AVAILABLE:
        print("🚀 Starting ngrok tunnel...")
        public_url = start_ngrok_tunnel(port)
        
        if public_url:
            print(f"✅ ngrok tunnel established!")
            print(f"🌐 Public URL: {public_url}")
        else:
            print("⚠️ ngrok tunnel failed, running local only")
    
    # Print access information
    print("="*70)
    print("🌐 ACCESS URLS:")
    if public_url:
        print(f"   • Worldwide: {public_url}")
    print(f"   • Local:     http://localhost:{port}")
    print(f"   • Network:   http://127.0.0.1:{port}")
    print("="*70)
    print("🔧 TEST ENDPOINTS:")
    base_url = public_url if public_url else f"http://localhost:{port}"
    print(f"   • Health:    {base_url}/api/health")
    print(f"   • Main page: {base_url}/")
    print("="*70)
    print("⚠️  NOTE: This is a simplified test version")
    print("   • Uses mock data for analysis")
    print("   • Placeholder images for Punnett squares")
    print("   • Basic text reports")
    print("="*70)
    
    # Start Flask server
    try:
        print(f"🚀 Starting Flask server on port {port}...")
        app.run(host='0.0.0.0', port=port, debug=False)
    except Exception as e:
        print(f"❌ Failed to start server: {str(e)}")
        traceback.print_exc()

if __name__ == '__main__':
    main()